# vim: ft=dosini
#
# aerc Oxocarbon styleset
# set styleset-name=oxocarbon-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#d0d0d0
border.bg=#ffffff

title.fg=#f2f2f2
title.bg=#0f62fe
title.bold=true

header.fg=#ee5396
#header.bg=#ffffff
header.bold=true

tab.fg=#d0d0d0
tab.bg=#f2f2f2
tab.selected.fg=#f2f2f2
tab.selected.bg=#0f62fe

statusline_default.fg=#37474f
statusline_default.bg=#fafafa
statusline_error.fg=#ff6f00
statusline_success.fg=#08bdba

*error.bold=true
*error.fg=#ff6f00
*warning.fg=#be95ff
*success.fg=#08bdba

dirlist_*.bg=#ffffff
dirlist_*.fg=#37474f
dirlist_*.selected.bg=#d0d0d0
dirlist_*.selected.fg=#37474f

msglist_*.bg=#ffffff
msglist_*.fg=#37474f
msglist_*.selected.bg=#d0d0d0
#msglist_*.selected.fg=#37474f
msglist_unread.bold=true
msglist_unread.fg=#0f62fe
msglist_marked.fg=#ff6f00
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#f2f2f2
msglist_pill.bg=#d0d0d0
msglist_pill.reverse=false

part_*.fg=#37474f
part_*.bg=#fafafa
part_*.selected.fg=#37474f
part_*.selected.bg=#d0d0d0

completion_default.bg=#fafafa
completion_default.fg=#37474f
completion_default.selected.bg=#d0d0d0
completion_default.selected.fg=#37474f
completion_gutter.bg=#f2f2f2
completion_pill.bg=#d0d0d0
completion_pill.reverse=false

spinner.bg=#ffffff
spinner.fg=#37474f

selector_focused.bold=false
selector_focused.bg=#d0d0d0
selector_focused.fg=#37474f
selector_chooser.bold=false
selector_chooser.bg=#d0d0d0
selector_chooser.fg=#37474f
default.selected.bold=false
default.selected.fg=#37474f
default.selected.bg=#d0d0d0

[viewer]
url.underline=true
url.fg=#6f7f86
header.fg=#be95ff
signature.fg=#673ab7
diff_add.fg=#cef2f1
diff_del.fg=#fcddea
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#ff6f00
quote_2.fg=#42be65
quote_3.fg=#08bdba
quote_3.dim=true
quote_4.fg=#0f62fe
quote_4.dim=true
quote_x.fg=#90a4ae
quote_x.dim=true

