# vim: ft=dosini
#
# aerc Oxocarbon styleset
# set styleset-name=oxocarbon-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#393939
border.bg=#161616

title.fg=#262626
title.bg=#78a9ff
title.bold=true

header.fg=#ee5396
#header.bg=#161616
header.bold=true

tab.fg=#393939
tab.bg=#262626
tab.selected.fg=#262626
tab.selected.bg=#78a9ff

statusline_default.fg=#d0d0d0
statusline_default.bg=#131313
statusline_error.fg=#ee5396
statusline_success.fg=#08bdba

*error.bold=true
*error.fg=#ee5396
*warning.fg=#be95ff
*success.fg=#08bdba

dirlist_*.bg=#161616
dirlist_*.fg=#d0d0d0
dirlist_*.selected.bg=#393939
dirlist_*.selected.fg=#d0d0d0

msglist_*.bg=#161616
msglist_*.fg=#d0d0d0
msglist_*.selected.bg=#393939
#msglist_*.selected.fg=#d0d0d0
msglist_unread.bold=true
msglist_unread.fg=#78a9ff
msglist_marked.fg=#ff7eb6
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#262626
msglist_pill.bg=#393939
msglist_pill.reverse=false

part_*.fg=#d0d0d0
part_*.bg=#131313
part_*.selected.fg=#d0d0d0
part_*.selected.bg=#393939

completion_default.bg=#131313
completion_default.fg=#d0d0d0
completion_default.selected.bg=#393939
completion_default.selected.fg=#d0d0d0
completion_gutter.bg=#262626
completion_pill.bg=#393939
completion_pill.reverse=false

spinner.bg=#161616
spinner.fg=#d0d0d0

selector_focused.bold=false
selector_focused.bg=#393939
selector_focused.fg=#d0d0d0
selector_chooser.bold=false
selector_chooser.bg=#393939
selector_chooser.fg=#d0d0d0
default.selected.bold=false
default.selected.fg=#d0d0d0
default.selected.bg=#393939

[viewer]
url.underline=true
url.fg=#adadad
header.fg=#be95ff
signature.fg=#be95ff
diff_add.fg=#122f2f
diff_del.fg=#361c28
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#42be65
quote_2.fg=#42be65
quote_3.fg=#08bdba
quote_3.dim=true
quote_4.fg=#78a9ff
quote_4.dim=true
quote_x.fg=#525252
quote_x.dim=true

