# Theme: oxocarbon_dark
# By: whispcat

theme[main_bg]="#161616"
theme[main_fg]="#d0d0d0"

# Title color for boxes
theme[title]="#d0d0d0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ff7eb6"

# Selected item in processes box
theme[selected_bg]="#262626"
theme[selected_fg]="#3ddbd9"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#3ddbd9"

# Cpu box outline color
theme[cpu_box]="#393939"

# Memory/disks box outline color
theme[mem_box]="#393939"

# Net up/down box outline color
theme[net_box]="#393939"

# Processes box outline color
theme[proc_box]="#393939"

# Box divider line and small boxes line color
theme[div_line]="#393939"

# Temperature graph colors
theme[temp_start]="#42be65"
theme[temp_mid]="#42be65"
theme[temp_end]="#ee5396"

# CPU graph colors
theme[cpu_start]="#42be65"
theme[cpu_mid]="#42be65"
theme[cpu_end]="#ee5396"

# Mem/Disk free meter
theme[free_start]="#42be65"
theme[free_mid]="#42be65"
theme[free_end]="#ee5396"

# Mem/Disk cached meter
theme[cached_start]="#42be65"
theme[cached_mid]="#42be65"
theme[cached_end]="#ee5396"

# Mem/Disk available meter
theme[available_start]="#42be65"
theme[available_mid]="#42be65"
theme[available_end]="#ee5396"

# Mem/Disk used meter
theme[used_start]="#42be65"
theme[used_mid]="#42be65"
theme[used_end]="#ee5396"

# Download graph colors
theme[download_start]="#42be65"
theme[download_mid]="#42be65"
theme[download_end]="#ee5396"

# Upload graph colors
theme[upload_start]="#42be65"
theme[upload_mid]="#42be65"
theme[upload_end]="#ee5396"