[[themes]]
name = "Oxocarbon Dark"
[themes.palette]
background = "#131313"
foreground = "#d0d0d0"
black = "#525252"
red = "#ee5396"
green = "#42be65"
yellow = "#42be65"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#3ddbd9"
white = "#f2f2f2"
bright_black = "#161616"
bright_red = "#ee5396"
bright_green = "#08bdba"
bright_yellow = "#ff7eb6"
bright_blue = "#3ddbd9"
bright_magenta = "#ee5396"
bright_cyan = "#82cfff"
bright_white = "#d0d0d0"
