[[themes]]
name = "Oxocarbon Light"
[themes.palette]
background = "#fafafa"
foreground = "#37474f"
black = "#90a4ae"
red = "#ee5396"
green = "#42be65"
yellow = "#ff6f00"
blue = "#0f62fe"
magenta = "#673ab7"
cyan = "#08bdba"
white = "#90a4ae"
bright_black = "#ffffff"
bright_red = "#ee5396"
bright_green = "#08bdba"
bright_yellow = "#ff6f00"
bright_blue = "#0f62fe"
bright_magenta = "#ee5396"
bright_cyan = "#0f62fe"
bright_white = "#37474f"
