# vim:ft=kitty

## name: Oxocarbon Light
## license: MIT
## author: whispcat (palette: nyoom-engineering/oxocarbon.nvim)
## upstream: https://github.com/whispcat/oxocarbon.theme/raw/main/extras/kitty/oxocarbon_light.conf


background #ffffff
foreground #37474f
selection_background #d0d0d0
selection_foreground #37474f
url_color #08bdba
cursor #37474f
cursor_text_color #ffffff

# Tabs
active_tab_background #0f62fe
active_tab_foreground #fafafa
inactive_tab_background #f2f2f2
inactive_tab_foreground #90a4ae
#tab_bar_background #f2f2f2

# Windows
active_border_color #0f62fe
inactive_border_color #f2f2f2

# normal
color0 #f2f2f2
color1 #0f62fe
color2 #be95ff
color3 #42be65
color4 #ee5396
color5 #ffab91
color6 #ff7eb6
color7 #90a4ae

# bright
color8  #161616
color9  #0f62fe
color10 #be95ff
color11 #42be65
color12 #ee5396
color13 #ffab91
color14 #08bdba
color15 #525252

# extended colors
color16 #ff6f00
color17 #ee5396
