# vim:ft=kitty

## name: Oxocarbon Dark
## license: MIT
## author: whispcat (palette: nyoom-engineering/oxocarbon.nvim)
## upstream: https://github.com/whispcat/oxocarbon.theme/raw/main/extras/kitty/oxocarbon_dark.conf


background #161616
foreground #d0d0d0
selection_background #393939
selection_foreground #d0d0d0
url_color #08bdba
cursor #d0d0d0
cursor_text_color #161616

# Tabs
active_tab_background #78a9ff
active_tab_foreground #131313
inactive_tab_background #262626
inactive_tab_foreground #525252
#tab_bar_background #262626

# Windows
active_border_color #78a9ff
inactive_border_color #262626

# normal
color0 #262626
color1 #33b1ff
color2 #be95ff
color3 #42be65
color4 #78a9ff
color5 #82cfff
color6 #3ddbd9
color7 #f2f2f2

# bright
color8  #525252
color9  #33b1ff
color10 #be95ff
color11 #42be65
color12 #78a9ff
color13 #82cfff
color14 #08bdba
color15 #ffffff

# extended colors
color16 #ff7eb6
color17 #ee5396
